Document what users are created in bootstrap.
bornhack/bornhack-website pull request #1314
Opened 2023-05-18 12:47 UTC by ramarrom

2023-05-19 10:43 UTC, tykling requested changes

2023-05-19 10:43 UTC, tykling commented on README.md
> +(venv) $ bornhack dbshell -- -c 'select email, username as password from auth_user;'
what is the `bornhack` command here?

2023-05-19 10:51 UTC, ramarrom commented
Oops. "bornhack" is my wrapper for manage.py. I fixed it.

2023-07-11 19:10 UTC, tykling approved these changes

2023-07-11 19:11 UTC, merged